-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 29, 2023 at 11:04 AM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `music_user`
--

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

use music_database;

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `user` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(100) NOT NULL,
  `dt` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

create table `active`(
	`user` varchar(255) NOT NULL
);

create table `active_song`(
	`song` int NOT NULL
);
insert into `active_song` value (3);
--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `user`, `email`, `password`, `dt`) VALUES
(1, 'user1', 'user1@gmail.com', '123456', '2023-04-26 04:31:26');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);
--
-- Database: `music_cmt`
--

-- --------------------------------------------------------

--
-- Table structure for table `comments`
--
CREATE TABLE `comments` (
  `CommentID` int(11) primary key auto_increment,
  `SongID` int(11),
  `UserID` int(11),
  `CommentText` varchar(1000),
  `CommentDate` timestamp
);
-- --------------------------------------------------------

--
-- Table structure for table `replies`
--

CREATE TABLE `replies` (
  `ReplyID` int(11) NOT NULL,
  `CommentID` int(11) NOT NULL,
  `UserID` int(11) NOT NULL,
  `ReplyText` varchar(1000) NOT NULL,
  `ReplyDate` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `songs`
--

CREATE TABLE `songs` (
  `id` int(11) NOT NULL primary key auto_increment,
  `songName` varchar(200),
  `poster` varchar(100),
  `lyric` text,
  `audio` text,
  `songDate` timestamp
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
-- --------------------------------------------------------

CREATE TABLE `likes` (
  `id` int(11) NOT NULL primary key auto_increment,
  `songID` int
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
insert into likes values(1,6);insert into likes values(2,7);
CREATE TABLE `library` (
  `id` int(11) NOT NULL primary key auto_increment,
  `songID` int
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
insert into library values(1,6);insert into library values(2,7);
CREATE TABLE `playlist` (
  `id` int(11) NOT NULL primary key auto_increment,
  `songID` int
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
insert into playlist values(1,6);
insert into playlist values(2,7);
insert into playlist values(3,8);
insert into playlist values(4,9);
insert into playlist values(5,10);
insert into playlist values(6,11);
insert into playlist values(7,12);
insert into playlist values(8,13);
insert into playlist values(9,14);
insert into playlist values(10,15);
insert into playlist values(11,16);
insert into playlist values(12,17);
insert into playlist values(13,18);
insert into playlist values(14,19);
insert into playlist values(15,20);

CREATE TABLE `category` (
  `category_id` int(11) NOT NULL primary key auto_increment,
  `category_name` varchar(50) NOT NULL,
  `description` varchar(225) NOT NULL
);

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `UserID` int(11) NOT NULL,
  `Username` varchar(50) NOT NULL,
  `Password` varchar(50) NOT NULL,
  `Email` varchar(100) NOT NULL,
  `Avatar` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `comments`
--
-- ALTER TABLE `comments`
--   ADD KEY `SongID` (`SongID`),
--   ADD KEY `UserID` (`UserID`);

--
-- Indexes for table `replies`
--
ALTER TABLE `replies`
  ADD PRIMARY KEY (`ReplyID`),
  ADD KEY `CommentID` (`CommentID`),
  ADD KEY `UserID` (`UserID`);

--
-- Indexes for table `songs`
--
--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`UserID`);

--
-- Constraints for dumped tables
--

--
-- Constraints for table `replies`
--
ALTER TABLE `replies`
  ADD CONSTRAINT `replies_ibfk_1` FOREIGN KEY (`CommentID`) REFERENCES `comments` (`CommentID`),
  ADD CONSTRAINT `replies_ibfk_2` FOREIGN KEY (`UserID`) REFERENCES `users` (`UserID`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

INSERT INTO songs value(1,'Nếu lúc đó<br><div class="subtitle">Tlinh</div>','img/1.jpg','Nếu lúc đó em không buông tay Nếu lúc đó anh không lung lay Nếu lúc đó ta không trốn chạy Không giấu những thứ không muốn nhau thấy Nếu lúc đó mình đặt lên nhau Nụ hôn đắm đuối như thể lần đầu Nếu lúc đó mình đừng giả vờ Nếu lúc đó mình đừng giả vờ Vờ như mọi thứ không làm mình đau Nếu lúc đó thế giới Đừng quá ác độc với hai đứa nhóc Không thể cho phép mình yếu lòng Vì quá quen việc phải gai góc Những vết cắt chưa lành được Rồi lại gồng mình, chẳng còn biết khóc Và nếu em không, và nếu em không Và nếu lúc đó em không ám ảnh Một ngày anh sẽ biến mất Và nếu lúc đó anh cho em thấy Em luôn là người duy nhất Và nếu lúc đó mà em tin anh Mà anh tin em Mà ta tin nhau Thì liệu mình sẽ còn ở bên nhau Liệu mình sẽ còn ở bên nhau Cười mỗi khi nghe thấy tên nhau Liệu mình đang còn đắm say đắm say Như ngày đầu tiên mình đến bên nhau Ngày em đã thức hàng đêm Để nguyện cầu Ngày em tự hứa dù có thế nào Em sẽ vẫn yêu anh Liệu mình còn yêu Nếu lúc đó ta không buông tay Yeah yeah Nếu lúc đó ta không trốn chạy oh Và nếu lúc đó mình đừng như thế yeah Có lẽ, có lẽ Nhưng có lẽ Mọi thứ đã phải diễn ra như vậy Để em thấy em phải yêu mình Đã đến lúc em phải nhận ra Em đã luôn tự lừa dối con tim Vì nếu anh muốn anh đã tìm cách Nhưng anh chẳng hề gì Em ghét cái cách em luôn bào chữa Cho mọi lần anh vô tâm Em ghét cái cách Em nói em vẫn ok Khi em tủi hờn Ghét dư luận tàn nhẫn Ghét nghĩ đến anh nhiều quá mức Ghét việc phải giữ im lặng Tỏ ra mình không vướng bận Nhưng em cũng không ít lần Gây ra những lỗi lầm Thứ lỗi cho em Hứa với anh những điều Giờ chỉ là ảo mộng Thứ lỗi cho em Bước đi Vì em phải cần tự chữa lành mình Thứ lỗi cho em Cho phép mình Nhận tình yêu mới đến rồi Thứ lỗi cho em Tập chịu trách nhiệm Cho cảm xúc của mình Thứ lỗi cho em Trân trọng những gì em đang có Thứ lỗi cho em Em mong anh cũng vậy Để một ngày Mình sẽ lại đến bên nhau Một ngày mình sẽ lại đến bên nhau Cười khi bắt gặp ánh mắt nhau Dù mình sẽ không còn đắm say đắm say Như ngày đầu tiên mình đến bên nhau Nhưng mình có thể Làm quen lại từ đầu Chẳng còn một nỗi sợ hãi Hay nghi ngờ nào nữa đâu Anh thấy sao Anh thấy sao Anh nghĩ sao Anh nghĩ sao','audio/1.mp3','2019-02-12 06:22:25');


INSERT INTO songs value(2,'Hơn em chổ nào<br><div class="subtitle">Thùy Chi</div>','img/2.jpg','Tự dưng nghĩ hay lỗi do mình vội đi Giá như chậm hơn chẳng lỡ buông lời Với tình yêu mình sẽ bớt buồn hơn Tại đôi khi em chẳng thể hiểu được anh Trái tim này bên anh chăm sóc chữa lành Điều gì đã khiến anh vứt bỏ đi hết Phải chăng rằng người ta tốt hơn em chỗ nào Tại sao anh mang nỗi buồn giăng kín lối Tình yêu vốn đẹp bởi từ cả hai sẽ mang lại ngọt ngào Đâu phải làm cho nước mắt rơi đâu Phải chăng rằng người ta ở bên anh lúc buồn Cớ sao như vậy không tìm em lúc đấy Vậy khi mỗi em một mình người con gái luôn cần tìm Anh lại đang vui nơi ấy với ai Nước mắt lại rơi Tự dưng nghĩ hay lỗi do mình vội đi Giá như chậm hơn chẳng lỡ buông lời Với tình yêu mình sẽ bớt buồn hơn Tại đôi khi em chẳng thể hiểu được anh Trái tim này bên anh chăm sóc chữa lành Điều gì đã khiến anh vứt bỏ đi hết Phải chăng rằng người ta tốt hơn em chỗ nào Tại sao anh mang nỗi buồn giăng kín lối Tình yêu vốn đẹp bởi từ cả hai sẽ mang lại ngọt ngào Đâu phải làm cho nước mắt rơi đâu Phải chăng rằng người ta ở bên anh lúc buồn Cớ sao như vậy không tìm em lúc đấy Vậy khi mỗi em một mình người con gái luôn cần tìm Anh lại đang vui nơi ấy với ai Nước mắt lại rơi Em không thể tin mọi thứ như vậy Có ai đau khổ thế này Một lần sau cuối Cầu xin em đi mà Cố gắng níu giữ em được không Phải chăng rằng người ta tốt hơn em chỗ nào Tại sao anh mang nỗi buồn giăng kín lối Tình yêu vốn đẹp bởi từ cả hai sẽ mang lại ngọt ngào Đâu phải làm cho nước mắt rơi đâu Phải chăng rằng người ta ở bên anh lúc buồn Cớ sao như vậy không tìm em lúc đấy Vậy khi mỗi em một mình người con gái luôn cần tìm Anh lại đang vui nơi ấy với ai Nước mắt lại rơi','audio/2.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(3,'Hơn cả yêu<br><div class="subtitle">Đức Phúc</div>','img/3.jpg','Em hay hỏi anh Rằng anh yêu em nhiều không? Anh không biết phải nói thế nào Để đúng với cảm xúc trong lòng Khi anh nhìn em Là anh thấy cuộc đời anh Là quá khứ và cả tương lai Là hiện tại không bao giờ phai Tình yêu trong anh vẫn luôn thầm lặng Nhưng không có nghĩa không rộng lớn Chỉ là anh đôi khi khó nói nên lời Mong em hãy cảm nhận thôi Cao hơn cả núi, dài hơn cả sông Rộng hơn cả đất, xanh hơn cả trời Anh yêu em, anh yêu em nhiều thế thôi Vượt qua ngọn gió, vượt qua đại dương Vượt qua cả những áng mây thiên đường Dẫu có nói bao điều Cảm giác trong anh bây giờ có lẽ hơn cả yêu Anh vẫn còn nhớ Lần đầu tiên ta gặp nhau Chẳng biết trước lần đó sẽ là Lần cuối anh yêu một ai trên đời Anh không còn mơ Gặp và yêu ai được nữa Giờ anh đã có em đây rồi Cùng em đi hết quãng đường đời Tình yêu trong anh vẫn luôn thầm lặng Nhưng không có nghĩa không rộng lớn Chỉ là anh đôi khi khó nói nên lời Mong em hãy cảm nhận thôi Cao hơn cả núi, dài hơn cả sông Rộng hơn cả đất, xanh hơn cả trời Anh yêu em, anh yêu em nhiều thế thôi Vượt qua ngọn gió, vượt qua đại dương Vượt qua cả những áng mây thiên đường Dẫu có nói bao điều Cảm giác trong anh bây giờ có lẽ hơn cả yêu Cao hơn cả núi, dài hơn cả sông Rộng hơn cả đất, xanh hơn cả trời Anh yêu em, anh yêu em nhiều thế thôi Vượt qua ngọn gió, vượt qua đại dương Vượt qua cả những áng mây thiên đường Dẫu có nói bao nhiêu Cảm giác trong anh bây giờ có lẽ hơn cả yêu Cảm giác trong anh bây giờ Có lẽ hơn cả yêu','audio/3.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(4,'Ngủ một mình<br><div class="subtitle">Hieuthuhai</div>','img/4.jpg',"Hãy ở lại với anh thêm một ngày nữa thôi Vì anh không muốn phải ngủ một mình đêm nay đâu Bên ngoài và uống say hay là ta nằm đây cả đêm Chỉ là anh không muốn phải ngủ một mình đêm nay Yeah yeah Baby nói cho anh nghe em hãy nói cho anh nghe những điều mà Điều em muốn sau khi đêm nay trôi qua Là một trái tim hay những món quà Em muốn đôi tay anh đặt ở những nơi đâu Anh đã nhắm đôi môi từ những ngày đầu I'm needing all your love Nhưng em sẽ chẳng thể thấy anh khi qua ngày mai Bởi vì thiên bình đây chẳng thể nào bên ai mãi mãi Hãy hứa không nói cho ai Hình em gửi anh làm sao mà có thể yeah Thay những khi mà em đằng sau nằm ôm anh Hãy ở lại với anh thêm một ngày nữa thôi Vì anh không muốn phải ngủ một mình đêm nay đâu Bên ngoài và uống say hay là ta nằm đây cả đêm Bởi vì anh không muốn phải ngủ một mình đêm nay Chẳng phải đón hay đưa Cứ việc lên nhà anh như cách em từng đến thôi Đây đâu phải là lần duy nhất của em ở đây Uh dù là ta chẳng phải của nhau Nhưng chỉ mình anh được hôn lên tóc em Chẳng phải quay mặt về nơi khác lúc em thay đồ Hoh oh Anh biết điều đó là sai nhưng không cho em gặp ai Phải ở bên anh đến ngày mai yah Phải ở đến ngày mai yah Bởi vì chúng ta cũng chỉ là Hai con người cô đơn đến với nhau Hãy ở lại với anh thêm một ngày nữa thôi Vì anh không muốn phải ngủ một mình đêm nay đâu Bên ngoài và uống say hay là ta nằm đây cả đêm Chỉ là anh không muốn phải ngủ một mình đêm nay Bởi vì anh không muốn phải ngủ một mình đêm nay Chỉ là anh không muốn phải ngủ một mình đêm nay Yeah yeah Baby nói cho anh nghe baby nói cho anh nghe những điều là",'audio/4.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(5,'Sau tất cả<br><div class="subtitle">Erik</div>','img/5.jpg','Ѕau tất cả mình lại trở về với nhau Tựa như chưa bắt đầu tựa như ta vừa mới quen Ѕau tất cả long chẳng hề đổi thaу Từng ngàу xa lìa khiến con tim bồi hồi Và ta lại gần nhau hơn nữa Ϲó những lúc đôi ta giận hờn Thầm trách nhau không một ai nói điều gì Thời gian cứ chậm lại từng giâу phút sao quá dài Để khiến anh nhận ra mình cần em hơn Ϲhorus: Tình уêu cứ thế đong đầу trong anh từng ngàу Vì quá уêu em nên không thể làm gì khác Ϲhỉ cần ta mãi luôn dành cho nhau những chân thành Mọi khó khan cũng chỉ là thử thách Vì trái tim ta luôn luôn thuộc về nhau Ứ ư ừ ư Lần 2: Ѕau tất cả mình lại chung lối đi Đoạn đường ta có nhau, bàn taу nắm chặt bấу lâu Ѕau tất cả mình cùng nhau sẻ chia Muộn phiền không thể khiến đôi tim nhạt nhoà Và ta lại gần nhau hơn nữa Ϲó những lúc đôi ta giận hờn Thầm trách nhau không một ai nói điều gì Thời gian cứ chậm lại từng giâу phút sao quá dài Để khiến anh nhận ra mình cần em hơn Ϲhorus: Tình уêu cứ thế đong đầу trong anh từng ngàу Vì quá уêu em nên không thể làm gì khác Ϲhỉ cần ta mãi luôn dành cho nhau những chân thành Mọi khó khan cũng chỉ là thử thách Vì trái tim ta luôn luôn thuộc về nhau Giữ chặt bàn taу mình cùng nhau đi hết bao tháng ngàу Mọi điều gian khó ta luôn vượt qua Để khiến ta nhận ra mình gần nhau hơn','audio/5.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(6,'Tình yêu đến sau<br><div class="subtitle">Myra Trần</div>','img/6.jpg','Gió đưa làn mây nhẹ trôi về đây Thoáng nghe mùi hương thật quen thật nhớ Chính anh tình yêu mà em mộng mơ Có nhau ngày sau là điều em ước ao Giấc mơ nhỏ nhoi được yêu người thôi Vẫn luôn hằng đêm chờ mong người sánh đôi Thế sao giờ đây dưới mưa phùn bay Nụ hôn người trao ai đấy Vờ như chẳng thấy đau một tình yêu đến sau Vờ như chẳng khát khao một vài câu nhớ nhau Vờ như chẳng thất vọng chẳng nhớ mong Mà sao lại không ngừng yếu lòng Càng mơ mộng đến đâu càng chìm trong hố sâu Mải mê tìm kiếm một lời nói yêu quá lâu Dẫu cho ngày sau có trăm lần đau em chẳng sao Giấc mơ nhỏ nhoi được yêu người thôi Vẫn luôn hằng đêm chờ mong người sánh đôi Thế sao giờ đây dưới mưa phùn bay Nụ hôn người trao ai đấy woh Vờ như chẳng thấy đau một tình yêu đến sau Vờ như chẳng khát khao một vài câu nhớ nhau Vờ như chẳng thất vọng chẳng nhớ mong Mà sao lại không ngừng yếu lòng Càng mơ mộng đến đâu càng chìm trong hố sâu Mải mê tìm kiếm một lời nói yêu quá lâu Dẫu cho ngày sau có trăm lần đau em chẳng sao oh Chẳng thể quên đi yêu thương giấu trong tim này Chẳng thể xoá hết kí ức đã theo bao ngày Còn lại em trong cơn say chìm vào cô đơn nơi đây anh có thấy Vờ như chẳng thấy đau một tình yêu đến sau Vờ như chẳng khát khao một vài câu nhớ nhau Vờ như chẳng thất vọng chẳng nhớ mong Mà sao lại không ngừng yếu lòng Càng mơ mộng đến đâu càng chìm trong hố sâu Mải mê tìm kiếm một lời nói yêu quá lâu Dẫu cho ngày sau có trăm lần đau em chẳng sao Dẫu cho ngày sau có trăm lần đau em chẳng sao','audio/6.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(7,'Tát nước đầu đình<br><div class="subtitle">Binz - Lynk Lee</div>','img/7.jpg','Anh sẽ chờ em Dù biển xanh kia có cạn khô Dù qua thêm bao kiếp Anh vẫn sẽ chờ Nhân thế khổ đau Tìm hoài sao không thấy nhau Người thương chẳng thương mình Còn người không thương cứ theo ta cả một đời Cây đã già nua Chờ ngày chết cách xa cõi đời Chiều hoàng hôn buông xuống phía tây nghẹn ngào Uống chén tình say Hoạ người thương trong bức tranh Hoạ ánh mắt anh buồn Hoạ nụ cười thêm trên nét môi Nhưng sao không được Nhiều lần em muốn anh vui mà thôi Hoạ vào nét môi anh nở cười tươi Dòng lệ rớt rơi phai màu Nhoè đi nụ cười khi ấy Lòng thì đau đớn trong em khổ đau Mà chẳng dám khóc đâu ai hiểu thấu Vẫn hoạ thêm chiếc môi cười tiếp theo Nhưng đau thấu trời Cây đã già nua Chờ ngày chết cách xa cõi đời Chiều hoàng hôn buông xuống phía tây nghẹn ngào Lỡ chén tình say Hoạ người thương trong bức tranh Hoạ ánh mắt anh buồn Tìm nụ cười anh trên nét môi Nhưng sao chẳng thấy Nhiều lần em muốn anh vui mà thôi Hoạ vào nét môi anh nở cười tươi Dòng lệ rớt rơi phai màu Nhoè đi nụ cười khi ấy Lòng thì đau đớn trong em khổ đau Mà chẳng dám khóc đâu ai hiểu thấu Vẫn hoạ thêm chiếc môi cười tiếp theo Nhưng đau thấu trời Khóc thật nhiều Ngồi khóc thật nhiều Khóc cho đời phong ba lắm đau mà chẳng nói ra Đến khi già Buồn hết một đời Đớn đau này của anh sẽ cao hơn trời Nhiều lần em muốn anh vui mà thôi Hoạ vào nét môi em nở cười tươi Dòng lệ rớt rơi phai màu Nhoè đi nụ cười khi ấy Lòng thì đau đớn trong em khổ đau Mà chẳng dám khóc đâu ai hiểu thấu Vẫn hoạ thêm chiếc môi cười tiếp theo Nhưng đau ai thấu Vẫn hoạ thêm chiếc môi cười lần nữa Nhưng đau ai thấu?','audio/7.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(8,'Là do em xui thôi<br><div class="subtitle">SOFIA x KHÓI x CHÂU ĐĂNG KHOA - </div>','img/8.jpg','Lộp độp từng hạt mưa, thả mình trên gương cửa Rồi bất lực trôi theo hoài niệm lăn dài dưới tường xưa Tưởng chưa thể quên nhưng mà đâu còn nhớ Ngoại trừ mỗi lời hứa yêu nhau đến khi nào còn thở Ừ thì ta đã lỡ chuyến xe về mà không hay Trong tay em giờ là chiếc buồn cùng ai khác vậy Vẫn ngân lên câu hát ấy, vòng hợp âm, khúc nhạc này Hay nhắc cho ai khác thấy nay thanh xuân tóc đã bạc đầy Chẳng một ai quan tâm em đâu em ơi, nên em chớ rơi lệ Hứa rằng em sẽ vui lên dẫu không ai đón đưa về Buồn làm chi em ơi mọi muộn phiền giờ thành chuyện cũ qua rồi Họ đã quên, em còn nhớ chi em ơi Chuyện tình yêu đôi khi chỉ là chuyện một người lừa dối một người Hứa hẹn cho vui thôi em ơi do em cả tin rồi Bởi vì em xứng đáng tìm được một người tuyệt vời nhất trên đời Nếu mà không được là do em xui thôi Ừ thì cuộc đời này chỉ toàn là dối trá Điều gì mà lại chả phải phôi pha Yêu thương hứa hẹn nhiều thế rồi mà Lời nói đều vô nghĩa qua môi cả Ừ thì hạnh phúc cũng chỉ để trôi xa Giận hờn, sao luôn lấy cái tôi ra? Thôi đi, em giờ đã mệt mỏi quá rồi thì Chẳng một ai quan tâm em đâu em ơi, nên em chớ rơi lệ Hứa rằng em sẽ vui lên dẫu không ai đón đưa về Buồn làm chi em ơi mọi muộn phiền giờ thành chuyện cũ qua rồi Họ đã quên, em còn nhớ chi em ơi Chuyện tình yêu đôi khi chỉ là chuyện một người lừa dối một người Hứa hẹn cho vui thôi em ơi do em cả tin rồi Bởi vì em xứng đáng tìm được một người tuyệt vời nhất Nếu mà không được là do em xui thôi Em nhấc bước chân nặng nề, dõi theo từng con phố vắng Đường về hóa lê thê vì lòng kia trĩu nặng Em ngước lên trời tự hỏi rằng mình đã làm gì sai chăng? Em ước chọn lý trí thay vì để con tim phải thắng Em khóc cho những thứ mà mình từng mơ Những kế hoạch mà em đang tự nhủ lòng mình đừng nhớ Em lại khóc cho chuyện tình không may từng lỡ Em khóc thật nhiều nhận lại chả có gì ngoài dăm ba hững hờ Chẳng một ai quan tâm em đâu em ơi, nên em chớ rơi lệ Hứa rằng em sẽ vui lên dẫu không ai đón đưa về Buồn làm chi em ơi mọi muộn phiền giờ thành chuyện đã qua Họ đã quên, em còn nhớ chi em ơi Bởi chuyện tình yêu đôi khi chỉ là chuyện một người lừa dối một người Hứa hẹn cho vui thôi em ơi do em cả tin rồi Bởi vì em xứng đáng tìm được một người tuyệt vời nhất trên đời Nếu mà không được là do em xui thôi Em khao khát có chỗ dựa vui buồn còn kể nhau nghe Nhưng chuyện cũ vẫn cứ luôn vẻ vẻ như ve đầu hè Em để niềm đau xâu xé, khi cơn mưa mãi rưng rưng Em lên chuyến tàu, cho kịp bến nhưng chân lại bước ung dung Em ghét thấy mình lúng túng, nên mặc vết thương âm ỉ Tiếng yêu nay hóa lùng bùng, chỉ còn hờn ghen thầm thì Sao em không thoát ra đi? Em giữ mình nơi quá an toàn, rồi lỡ có... Buồn thì lấy gì để nhâm nhi?','audio/8.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(9,'Ưng quá chừng<br><div class="subtitle">Amee</div>','img/9.jpg','Anh sẽ chờ em Dù biển xanh kia có cạn khô Dù qua thêm bao kiếp Anh vẫn sẽ chờ Nhân thế khổ đau Tìm hoài sao không thấy nhau Người thương chẳng thương mình Còn người không thương cứ theo ta cả một đời Cây đã già nua Chờ ngày chết cách xa cõi đời Chiều hoàng hôn buông xuống phía tây nghẹn ngào Uống chén tình say Hoạ người thương trong bức tranh Hoạ ánh mắt anh buồn Hoạ nụ cười thêm trên nét môi Nhưng sao không được Nhiều lần em muốn anh vui mà thôi Hoạ vào nét môi anh nở cười tươi Dòng lệ rớt rơi phai màu Nhoè đi nụ cười khi ấy Lòng thì đau đớn trong em khổ đau Mà chẳng dám khóc đâu ai hiểu thấu Vẫn hoạ thêm chiếc môi cười tiếp theo Nhưng đau thấu trời Cây đã già nua Chờ ngày chết cách xa cõi đời Chiều hoàng hôn buông xuống phía tây nghẹn ngào Lỡ chén tình say Hoạ người thương trong bức tranh Hoạ ánh mắt anh buồn Tìm nụ cười anh trên nét môi Nhưng sao chẳng thấy Nhiều lần em muốn anh vui mà thôi Hoạ vào nét môi anh nở cười tươi Dòng lệ rớt rơi phai màu Nhoè đi nụ cười khi ấy Lòng thì đau đớn trong em khổ đau Mà chẳng dám khóc đâu ai hiểu thấu Vẫn hoạ thêm chiếc môi cười tiếp theo Nhưng đau thấu trời Khóc thật nhiều Ngồi khóc thật nhiều Khóc cho đời phong ba lắm đau mà chẳng nói ra Đến khi già Buồn hết một đời Đớn đau này của anh sẽ cao hơn trời Nhiều lần em muốn anh vui mà thôi Hoạ vào nét môi em nở cười tươi Dòng lệ rớt rơi phai màu Nhoè đi nụ cười khi ấy Lòng thì đau đớn trong em khổ đau Mà chẳng dám khóc đâu ai hiểu thấu Vẫn hoạ thêm chiếc môi cười tiếp theo Nhưng đau ai thấu Vẫn hoạ thêm chiếc môi cười lần nữa Nhưng đau ai thấu?','audio/9.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(10,'Nhạc Anh<br><div class="subtitle">Andree ft Wxrdie</div>','img/10.jpg','Lộp độp từng hạt mưa, thả mình trên gương cửa Rồi bất lực trôi theo hoài niệm lăn dài dưới tường xưa Tưởng chưa thể quên nhưng mà đâu còn nhớ Ngoại trừ mỗi lời hứa yêu nhau đến khi nào còn thở Ừ thì ta đã lỡ chuyến xe về mà không hay Trong tay em giờ là chiếc buồn cùng ai khác vậy Vẫn ngân lên câu hát ấy, vòng hợp âm, khúc nhạc này Hay nhắc cho ai khác thấy nay thanh xuân tóc đã bạc đầy Chẳng một ai quan tâm em đâu em ơi, nên em chớ rơi lệ Hứa rằng em sẽ vui lên dẫu không ai đón đưa về Buồn làm chi em ơi mọi muộn phiền giờ thành chuyện cũ qua rồi Họ đã quên, em còn nhớ chi em ơi Chuyện tình yêu đôi khi chỉ là chuyện một người lừa dối một người Hứa hẹn cho vui thôi em ơi do em cả tin rồi Bởi vì em xứng đáng tìm được một người tuyệt vời nhất trên đời Nếu mà không được là do em xui thôi Ừ thì cuộc đời này chỉ toàn là dối trá Điều gì mà lại chả phải phôi pha Yêu thương hứa hẹn nhiều thế rồi mà Lời nói đều vô nghĩa qua môi cả Ừ thì hạnh phúc cũng chỉ để trôi xa Giận hờn, sao luôn lấy cái tôi ra? Thôi đi, em giờ đã mệt mỏi quá rồi thì Chẳng một ai quan tâm em đâu em ơi, nên em chớ rơi lệ Hứa rằng em sẽ vui lên dẫu không ai đón đưa về Buồn làm chi em ơi mọi muộn phiền giờ thành chuyện cũ qua rồi Họ đã quên, em còn nhớ chi em ơi Chuyện tình yêu đôi khi chỉ là chuyện một người lừa dối một người Hứa hẹn cho vui thôi em ơi do em cả tin rồi Bởi vì em xứng đáng tìm được một người tuyệt vời nhất Nếu mà không được là do em xui thôi Em nhấc bước chân nặng nề, dõi theo từng con phố vắng Đường về hóa lê thê vì lòng kia trĩu nặng Em ngước lên trời tự hỏi rằng mình đã làm gì sai chăng? Em ước chọn lý trí thay vì để con tim phải thắng Em khóc cho những thứ mà mình từng mơ Những kế hoạch mà em đang tự nhủ lòng mình đừng nhớ Em lại khóc cho chuyện tình không may từng lỡ Em khóc thật nhiều nhận lại chả có gì ngoài dăm ba hững hờ Chẳng một ai quan tâm em đâu em ơi, nên em chớ rơi lệ Hứa rằng em sẽ vui lên dẫu không ai đón đưa về Buồn làm chi em ơi mọi muộn phiền giờ thành chuyện đã qua Họ đã quên, em còn nhớ chi em ơi Bởi chuyện tình yêu đôi khi chỉ là chuyện một người lừa dối một người Hứa hẹn cho vui thôi em ơi do em cả tin rồi Bởi vì em xứng đáng tìm được một người tuyệt vời nhất trên đời Nếu mà không được là do em xui thôi Em khao khát có chỗ dựa vui buồn còn kể nhau nghe Nhưng chuyện cũ vẫn cứ luôn vẻ vẻ như ve đầu hè Em để niềm đau xâu xé, khi cơn mưa mãi rưng rưng Em lên chuyến tàu, cho kịp bến nhưng chân lại bước ung dung Em ghét thấy mình lúng túng, nên mặc vết thương âm ỉ Tiếng yêu nay hóa lùng bùng, chỉ còn hờn ghen thầm thì Sao em không thoát ra đi? Em giữ mình nơi quá an toàn, rồi lỡ có... Buồn thì lấy gì để nhâm nhi?','audio/10.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(11,'Real Love<br><div class="subtitle">Mỹ Anh - Khắc Hưng</div>','img/11.jpg','Ѕau tất cả mình lại trở về với nhau Tựa như chưa bắt đầu tựa như ta vừa mới quen Ѕau tất cả long chẳng hề đổi thaу Từng ngàу xa lìa khiến con tim bồi hồi Và ta lại gần nhau hơn nữa Ϲó những lúc đôi ta giận hờn Thầm trách nhau không một ai nói điều gì Thời gian cứ chậm lại từng giâу phút sao quá dài Để khiến anh nhận ra mình cần em hơn Ϲhorus: Tình уêu cứ thế đong đầу trong anh từng ngàу Vì quá уêu em nên không thể làm gì khác Ϲhỉ cần ta mãi luôn dành cho nhau những chân thành Mọi khó khan cũng chỉ là thử thách Vì trái tim ta luôn luôn thuộc về nhau Ứ ư ừ ư Lần 2: Ѕau tất cả mình lại chung lối đi Đoạn đường ta có nhau, bàn taу nắm chặt bấу lâu Ѕau tất cả mình cùng nhau sẻ chia Muộn phiền không thể khiến đôi tim nhạt nhoà Và ta lại gần nhau hơn nữa Ϲó những lúc đôi ta giận hờn Thầm trách nhau không một ai nói điều gì Thời gian cứ chậm lại từng giâу phút sao quá dài Để khiến anh nhận ra mình cần em hơn Ϲhorus: Tình уêu cứ thế đong đầу trong anh từng ngàу Vì quá уêu em nên không thể làm gì khác Ϲhỉ cần ta mãi luôn dành cho nhau những chân thành Mọi khó khan cũng chỉ là thử thách Vì trái tim ta luôn luôn thuộc về nhau Giữ chặt bàn taу mình cùng nhau đi hết bao tháng ngàу Mọi điều gian khó ta luôn vượt qua Để khiến ta nhận ra mình gần nhau hơn','audio/11.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(12,'Khó Vẽ Nụ Cười<br><div class="subtitle">Du Uyên ft Đạt G</div>','img/12.jpg','Anh sẽ chờ em Dù biển xanh kia có cạn khô Dù qua thêm bao kiếp Anh vẫn sẽ chờ Nhân thế khổ đau Tìm hoài sao không thấy nhau Người thương chẳng thương mình Còn người không thương cứ theo ta cả một đời Cây đã già nua Chờ ngày chết cách xa cõi đời Chiều hoàng hôn buông xuống phía tây nghẹn ngào Uống chén tình say Hoạ người thương trong bức tranh Hoạ ánh mắt anh buồn Hoạ nụ cười thêm trên nét môi Nhưng sao không được Nhiều lần em muốn anh vui mà thôi Hoạ vào nét môi anh nở cười tươi Dòng lệ rớt rơi phai màu Nhoè đi nụ cười khi ấy Lòng thì đau đớn trong em khổ đau Mà chẳng dám khóc đâu ai hiểu thấu Vẫn hoạ thêm chiếc môi cười tiếp theo Nhưng đau thấu trời Cây đã già nua Chờ ngày chết cách xa cõi đời Chiều hoàng hôn buông xuống phía tây nghẹn ngào Lỡ chén tình say Hoạ người thương trong bức tranh Hoạ ánh mắt anh buồn Tìm nụ cười anh trên nét môi Nhưng sao chẳng thấy Nhiều lần em muốn anh vui mà thôi Hoạ vào nét môi anh nở cười tươi Dòng lệ rớt rơi phai màu Nhoè đi nụ cười khi ấy Lòng thì đau đớn trong em khổ đau Mà chẳng dám khóc đâu ai hiểu thấu Vẫn hoạ thêm chiếc môi cười tiếp theo Nhưng đau thấu trời Khóc thật nhiều Ngồi khóc thật nhiều Khóc cho đời phong ba lắm đau mà chẳng nói ra Đến khi già Buồn hết một đời Đớn đau này của anh sẽ cao hơn trời Nhiều lần em muốn anh vui mà thôi Hoạ vào nét môi em nở cười tươi Dòng lệ rớt rơi phai màu Nhoè đi nụ cười khi ấy Lòng thì đau đớn trong em khổ đau Mà chẳng dám khóc đâu ai hiểu thấu Vẫn hoạ thêm chiếc môi cười tiếp theo Nhưng đau ai thấu Vẫn hoạ thêm chiếc môi cười lần nữa Nhưng đau ai thấu?','audio/12.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(13,'Ừ em xin lỗi<br><div class="subtitle">Hoàng Yến Chibi</div>','img/13.jpg','Gió đưa làn mây nhẹ trôi về đây Thoáng nghe mùi hương thật quen thật nhớ Chính anh tình yêu mà em mộng mơ Có nhau ngày sau là điều em ước ao Giấc mơ nhỏ nhoi được yêu người thôi Vẫn luôn hằng đêm chờ mong người sánh đôi Thế sao giờ đây dưới mưa phùn bay Nụ hôn người trao ai đấy Vờ như chẳng thấy đau một tình yêu đến sau Vờ như chẳng khát khao một vài câu nhớ nhau Vờ như chẳng thất vọng chẳng nhớ mong Mà sao lại không ngừng yếu lòng Càng mơ mộng đến đâu càng chìm trong hố sâu Mải mê tìm kiếm một lời nói yêu quá lâu Dẫu cho ngày sau có trăm lần đau em chẳng sao Giấc mơ nhỏ nhoi được yêu người thôi Vẫn luôn hằng đêm chờ mong người sánh đôi Thế sao giờ đây dưới mưa phùn bay Nụ hôn người trao ai đấy woh Vờ như chẳng thấy đau một tình yêu đến sau Vờ như chẳng khát khao một vài câu nhớ nhau Vờ như chẳng thất vọng chẳng nhớ mong Mà sao lại không ngừng yếu lòng Càng mơ mộng đến đâu càng chìm trong hố sâu Mải mê tìm kiếm một lời nói yêu quá lâu Dẫu cho ngày sau có trăm lần đau em chẳng sao oh Chẳng thể quên đi yêu thương giấu trong tim này Chẳng thể xoá hết kí ức đã theo bao ngày Còn lại em trong cơn say chìm vào cô đơn nơi đây anh có thấy Vờ như chẳng thấy đau một tình yêu đến sau Vờ như chẳng khát khao một vài câu nhớ nhau Vờ như chẳng thất vọng chẳng nhớ mong Mà sao lại không ngừng yếu lòng Càng mơ mộng đến đâu càng chìm trong hố sâu Mải mê tìm kiếm một lời nói yêu quá lâu Dẫu cho ngày sau có trăm lần đau em chẳng sao Dẫu cho ngày sau có trăm lần đau em chẳng sao','audio/13.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(14,'Yêu đương khó quá thì chạy về khóc với anh<br><div class="subtitle">Erik</div>','img/14.jpg','Anh sẽ chờ em Dù biển xanh kia có cạn khô Dù qua thêm bao kiếp Anh vẫn sẽ chờ Nhân thế khổ đau Tìm hoài sao không thấy nhau Người thương chẳng thương mình Còn người không thương cứ theo ta cả một đời Cây đã già nua Chờ ngày chết cách xa cõi đời Chiều hoàng hôn buông xuống phía tây nghẹn ngào Uống chén tình say Hoạ người thương trong bức tranh Hoạ ánh mắt anh buồn Hoạ nụ cười thêm trên nét môi Nhưng sao không được Nhiều lần em muốn anh vui mà thôi Hoạ vào nét môi anh nở cười tươi Dòng lệ rớt rơi phai màu Nhoè đi nụ cười khi ấy Lòng thì đau đớn trong em khổ đau Mà chẳng dám khóc đâu ai hiểu thấu Vẫn hoạ thêm chiếc môi cười tiếp theo Nhưng đau thấu trời Cây đã già nua Chờ ngày chết cách xa cõi đời Chiều hoàng hôn buông xuống phía tây nghẹn ngào Lỡ chén tình say Hoạ người thương trong bức tranh Hoạ ánh mắt anh buồn Tìm nụ cười anh trên nét môi Nhưng sao chẳng thấy Nhiều lần em muốn anh vui mà thôi Hoạ vào nét môi anh nở cười tươi Dòng lệ rớt rơi phai màu Nhoè đi nụ cười khi ấy Lòng thì đau đớn trong em khổ đau Mà chẳng dám khóc đâu ai hiểu thấu Vẫn hoạ thêm chiếc môi cười tiếp theo Nhưng đau thấu trời Khóc thật nhiều Ngồi khóc thật nhiều Khóc cho đời phong ba lắm đau mà chẳng nói ra Đến khi già Buồn hết một đời Đớn đau này của anh sẽ cao hơn trời Nhiều lần em muốn anh vui mà thôi Hoạ vào nét môi em nở cười tươi Dòng lệ rớt rơi phai màu Nhoè đi nụ cười khi ấy Lòng thì đau đớn trong em khổ đau Mà chẳng dám khóc đâu ai hiểu thấu Vẫn hoạ thêm chiếc môi cười tiếp theo Nhưng đau ai thấu Vẫn hoạ thêm chiếc môi cười lần nữa Nhưng đau ai thấu?','audio/14.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(15,'Lạc Trôi<br><div class="subtitle">Sơn Tùng</div>','img/15.jpg','Ѕau tất cả mình lại trở về với nhau Tựa như chưa bắt đầu tựa như ta vừa mới quen Ѕau tất cả long chẳng hề đổi thaу Từng ngàу xa lìa khiến con tim bồi hồi Và ta lại gần nhau hơn nữa Ϲó những lúc đôi ta giận hờn Thầm trách nhau không một ai nói điều gì Thời gian cứ chậm lại từng giâу phút sao quá dài Để khiến anh nhận ra mình cần em hơn Ϲhorus: Tình уêu cứ thế đong đầу trong anh từng ngàу Vì quá уêu em nên không thể làm gì khác Ϲhỉ cần ta mãi luôn dành cho nhau những chân thành Mọi khó khan cũng chỉ là thử thách Vì trái tim ta luôn luôn thuộc về nhau Ứ ư ừ ư Lần 2: Ѕau tất cả mình lại chung lối đi Đoạn đường ta có nhau, bàn taу nắm chặt bấу lâu Ѕau tất cả mình cùng nhau sẻ chia Muộn phiền không thể khiến đôi tim nhạt nhoà Và ta lại gần nhau hơn nữa Ϲó những lúc đôi ta giận hờn Thầm trách nhau không một ai nói điều gì Thời gian cứ chậm lại từng giâу phút sao quá dài Để khiến anh nhận ra mình cần em hơn Ϲhorus: Tình уêu cứ thế đong đầу trong anh từng ngàу Vì quá уêu em nên không thể làm gì khác Ϲhỉ cần ta mãi luôn dành cho nhau những chân thành Mọi khó khan cũng chỉ là thử thách Vì trái tim ta luôn luôn thuộc về nhau Giữ chặt bàn taу mình cùng nhau đi hết bao tháng ngàу Mọi điều gian khó ta luôn vượt qua Để khiến ta nhận ra mình gần nhau hơn','audio/15.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(16,'Dễ đến dễ đi<br><div class="subtitle">Quang Hùng MasterD</div>','img/16.jpg','Gió đưa làn mây nhẹ trôi về đây Thoáng nghe mùi hương thật quen thật nhớ Chính anh tình yêu mà em mộng mơ Có nhau ngày sau là điều em ước ao Giấc mơ nhỏ nhoi được yêu người thôi Vẫn luôn hằng đêm chờ mong người sánh đôi Thế sao giờ đây dưới mưa phùn bay Nụ hôn người trao ai đấy Vờ như chẳng thấy đau một tình yêu đến sau Vờ như chẳng khát khao một vài câu nhớ nhau Vờ như chẳng thất vọng chẳng nhớ mong Mà sao lại không ngừng yếu lòng Càng mơ mộng đến đâu càng chìm trong hố sâu Mải mê tìm kiếm một lời nói yêu quá lâu Dẫu cho ngày sau có trăm lần đau em chẳng sao Giấc mơ nhỏ nhoi được yêu người thôi Vẫn luôn hằng đêm chờ mong người sánh đôi Thế sao giờ đây dưới mưa phùn bay Nụ hôn người trao ai đấy woh Vờ như chẳng thấy đau một tình yêu đến sau Vờ như chẳng khát khao một vài câu nhớ nhau Vờ như chẳng thất vọng chẳng nhớ mong Mà sao lại không ngừng yếu lòng Càng mơ mộng đến đâu càng chìm trong hố sâu Mải mê tìm kiếm một lời nói yêu quá lâu Dẫu cho ngày sau có trăm lần đau em chẳng sao oh Chẳng thể quên đi yêu thương giấu trong tim này Chẳng thể xoá hết kí ức đã theo bao ngày Còn lại em trong cơn say chìm vào cô đơn nơi đây anh có thấy Vờ như chẳng thấy đau một tình yêu đến sau Vờ như chẳng khát khao một vài câu nhớ nhau Vờ như chẳng thất vọng chẳng nhớ mong Mà sao lại không ngừng yếu lòng Càng mơ mộng đến đâu càng chìm trong hố sâu Mải mê tìm kiếm một lời nói yêu quá lâu Dẫu cho ngày sau có trăm lần đau em chẳng sao Dẫu cho ngày sau có trăm lần đau em chẳng sao','audio/16.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(17,'Suýt nữa thì<br><div class="subtitle">Andiez</div>','img/17.jpg','Ѕau tất cả mình lại trở về với nhau Tựa như chưa bắt đầu tựa như ta vừa mới quen Ѕau tất cả long chẳng hề đổi thaу Từng ngàу xa lìa khiến con tim bồi hồi Và ta lại gần nhau hơn nữa Ϲó những lúc đôi ta giận hờn Thầm trách nhau không một ai nói điều gì Thời gian cứ chậm lại từng giâу phút sao quá dài Để khiến anh nhận ra mình cần em hơn Ϲhorus: Tình уêu cứ thế đong đầу trong anh từng ngàу Vì quá уêu em nên không thể làm gì khác Ϲhỉ cần ta mãi luôn dành cho nhau những chân thành Mọi khó khan cũng chỉ là thử thách Vì trái tim ta luôn luôn thuộc về nhau Ứ ư ừ ư Lần 2: Ѕau tất cả mình lại chung lối đi Đoạn đường ta có nhau, bàn taу nắm chặt bấу lâu Ѕau tất cả mình cùng nhau sẻ chia Muộn phiền không thể khiến đôi tim nhạt nhoà Và ta lại gần nhau hơn nữa Ϲó những lúc đôi ta giận hờn Thầm trách nhau không một ai nói điều gì Thời gian cứ chậm lại từng giâу phút sao quá dài Để khiến anh nhận ra mình cần em hơn Ϲhorus: Tình уêu cứ thế đong đầу trong anh từng ngàу Vì quá уêu em nên không thể làm gì khác Ϲhỉ cần ta mãi luôn dành cho nhau những chân thành Mọi khó khan cũng chỉ là thử thách Vì trái tim ta luôn luôn thuộc về nhau Giữ chặt bàn taу mình cùng nhau đi hết bao tháng ngàу Mọi điều gian khó ta luôn vượt qua Để khiến ta nhận ra mình gần nhau hơn','audio/17.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(18,'Mời anh vào Team em<br><div class="subtitle">Chi Pu</div>','img/18.jpg','Anh sẽ chờ em Dù biển xanh kia có cạn khô Dù qua thêm bao kiếp Anh vẫn sẽ chờ Nhân thế khổ đau Tìm hoài sao không thấy nhau Người thương chẳng thương mình Còn người không thương cứ theo ta cả một đời Cây đã già nua Chờ ngày chết cách xa cõi đời Chiều hoàng hôn buông xuống phía tây nghẹn ngào Uống chén tình say Hoạ người thương trong bức tranh Hoạ ánh mắt anh buồn Hoạ nụ cười thêm trên nét môi Nhưng sao không được Nhiều lần em muốn anh vui mà thôi Hoạ vào nét môi anh nở cười tươi Dòng lệ rớt rơi phai màu Nhoè đi nụ cười khi ấy Lòng thì đau đớn trong em khổ đau Mà chẳng dám khóc đâu ai hiểu thấu Vẫn hoạ thêm chiếc môi cười tiếp theo Nhưng đau thấu trời Cây đã già nua Chờ ngày chết cách xa cõi đời Chiều hoàng hôn buông xuống phía tây nghẹn ngào Lỡ chén tình say Hoạ người thương trong bức tranh Hoạ ánh mắt anh buồn Tìm nụ cười anh trên nét môi Nhưng sao chẳng thấy Nhiều lần em muốn anh vui mà thôi Hoạ vào nét môi anh nở cười tươi Dòng lệ rớt rơi phai màu Nhoè đi nụ cười khi ấy Lòng thì đau đớn trong em khổ đau Mà chẳng dám khóc đâu ai hiểu thấu Vẫn hoạ thêm chiếc môi cười tiếp theo Nhưng đau thấu trời Khóc thật nhiều Ngồi khóc thật nhiều Khóc cho đời phong ba lắm đau mà chẳng nói ra Đến khi già Buồn hết một đời Đớn đau này của anh sẽ cao hơn trời Nhiều lần em muốn anh vui mà thôi Hoạ vào nét môi em nở cười tươi Dòng lệ rớt rơi phai màu Nhoè đi nụ cười khi ấy Lòng thì đau đớn trong em khổ đau Mà chẳng dám khóc đâu ai hiểu thấu Vẫn hoạ thêm chiếc môi cười tiếp theo Nhưng đau ai thấu Vẫn hoạ thêm chiếc môi cười lần nữa Nhưng đau ai thấu?','audio/18.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(19,'Chúng ta không thuộc về nhau<br><div class="subtitle">Sơn Tùng MTP</div>','img/19.jpg','Ѕau tất cả mình lại trở về với nhau Tựa như chưa bắt đầu tựa như ta vừa mới quen Ѕau tất cả long chẳng hề đổi thaу Từng ngàу xa lìa khiến con tim bồi hồi Và ta lại gần nhau hơn nữa Ϲó những lúc đôi ta giận hờn Thầm trách nhau không một ai nói điều gì Thời gian cứ chậm lại từng giâу phút sao quá dài Để khiến anh nhận ra mình cần em hơn Ϲhorus: Tình уêu cứ thế đong đầу trong anh từng ngàу Vì quá уêu em nên không thể làm gì khác Ϲhỉ cần ta mãi luôn dành cho nhau những chân thành Mọi khó khan cũng chỉ là thử thách Vì trái tim ta luôn luôn thuộc về nhau Ứ ư ừ ư Lần 2: Ѕau tất cả mình lại chung lối đi Đoạn đường ta có nhau, bàn taу nắm chặt bấу lâu Ѕau tất cả mình cùng nhau sẻ chia Muộn phiền không thể khiến đôi tim nhạt nhoà Và ta lại gần nhau hơn nữa Ϲó những lúc đôi ta giận hờn Thầm trách nhau không một ai nói điều gì Thời gian cứ chậm lại từng giâу phút sao quá dài Để khiến anh nhận ra mình cần em hơn Ϲhorus: Tình уêu cứ thế đong đầу trong anh từng ngàу Vì quá уêu em nên không thể làm gì khác Ϲhỉ cần ta mãi luôn dành cho nhau những chân thành Mọi khó khan cũng chỉ là thử thách Vì trái tim ta luôn luôn thuộc về nhau Giữ chặt bàn taу mình cùng nhau đi hết bao tháng ngàу Mọi điều gian khó ta luôn vượt qua Để khiến ta nhận ra mình gần nhau hơn','audio/19.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(20,'Thích hay là yêu còn chưa biết<br><div class="subtitle">LONA - Ricky Star</div>','img/20.jpg','Ѕau tất cả mình lại trở về với nhau Tựa như chưa bắt đầu tựa như ta vừa mới quen Ѕau tất cả long chẳng hề đổi thaу Từng ngàу xa lìa khiến con tim bồi hồi Và ta lại gần nhau hơn nữa Ϲó những lúc đôi ta giận hờn Thầm trách nhau không một ai nói điều gì Thời gian cứ chậm lại từng giâу phút sao quá dài Để khiến anh nhận ra mình cần em hơn Ϲhorus: Tình уêu cứ thế đong đầу trong anh từng ngàу Vì quá уêu em nên không thể làm gì khác Ϲhỉ cần ta mãi luôn dành cho nhau những chân thành Mọi khó khan cũng chỉ là thử thách Vì trái tim ta luôn luôn thuộc về nhau Ứ ư ừ ư Lần 2: Ѕau tất cả mình lại chung lối đi Đoạn đường ta có nhau, bàn taу nắm chặt bấу lâu Ѕau tất cả mình cùng nhau sẻ chia Muộn phiền không thể khiến đôi tim nhạt nhoà Và ta lại gần nhau hơn nữa Ϲó những lúc đôi ta giận hờn Thầm trách nhau không một ai nói điều gì Thời gian cứ chậm lại từng giâу phút sao quá dài Để khiến anh nhận ra mình cần em hơn Ϲhorus: Tình уêu cứ thế đong đầу trong anh từng ngàу Vì quá уêu em nên không thể làm gì khác Ϲhỉ cần ta mãi luôn dành cho nhau những chân thành Mọi khó khan cũng chỉ là thử thách Vì trái tim ta luôn luôn thuộc về nhau Giữ chặt bàn taу mình cùng nhau đi hết bao tháng ngàу Mọi điều gian khó ta luôn vượt qua Để khiến ta nhận ra mình gần nhau hơn','audio/20.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(21,'WAP<br><div class="subtitle">Cardi B - Megan Thee Stallion</div>','img/21.jpg','Gió đưa làn mây nhẹ trôi về đây Thoáng nghe mùi hương thật quen thật nhớ Chính anh tình yêu mà em mộng mơ Có nhau ngày sau là điều em ước ao Giấc mơ nhỏ nhoi được yêu người thôi Vẫn luôn hằng đêm chờ mong người sánh đôi Thế sao giờ đây dưới mưa phùn bay Nụ hôn người trao ai đấy Vờ như chẳng thấy đau một tình yêu đến sau Vờ như chẳng khát khao một vài câu nhớ nhau Vờ như chẳng thất vọng chẳng nhớ mong Mà sao lại không ngừng yếu lòng Càng mơ mộng đến đâu càng chìm trong hố sâu Mải mê tìm kiếm một lời nói yêu quá lâu Dẫu cho ngày sau có trăm lần đau em chẳng sao Giấc mơ nhỏ nhoi được yêu người thôi Vẫn luôn hằng đêm chờ mong người sánh đôi Thế sao giờ đây dưới mưa phùn bay Nụ hôn người trao ai đấy woh Vờ như chẳng thấy đau một tình yêu đến sau Vờ như chẳng khát khao một vài câu nhớ nhau Vờ như chẳng thất vọng chẳng nhớ mong Mà sao lại không ngừng yếu lòng Càng mơ mộng đến đâu càng chìm trong hố sâu Mải mê tìm kiếm một lời nói yêu quá lâu Dẫu cho ngày sau có trăm lần đau em chẳng sao oh Chẳng thể quên đi yêu thương giấu trong tim này Chẳng thể xoá hết kí ức đã theo bao ngày Còn lại em trong cơn say chìm vào cô đơn nơi đây anh có thấy Vờ như chẳng thấy đau một tình yêu đến sau Vờ như chẳng khát khao một vài câu nhớ nhau Vờ như chẳng thất vọng chẳng nhớ mong Mà sao lại không ngừng yếu lòng Càng mơ mộng đến đâu càng chìm trong hố sâu Mải mê tìm kiếm một lời nói yêu quá lâu Dẫu cho ngày sau có trăm lần đau em chẳng sao Dẫu cho ngày sau có trăm lần đau em chẳng sao','audio/21.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(22,'Kiss me more<br><div class="subtitle">Doja Cat ft SZA</div>','img/22.jpg',"If you want it, take it I should have said it before Tried to hide it, fake it I can't pretend anymore I only want to die alive Never by the hands of a broken heart I don't wanna hear you lie tonight Now that I've become who I really am This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more You were better, deeper I was under your spell Like a deadly fear I am, babe On the highway to hell I only want to die alive Never by the hands of a broken heart I don't wanna hear you lie tonight Now that I've become who I really am This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more Thought of your body I came alive It was lethal It was fatal In my dreams it felt so right But I woke up every time Oh baby This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more",'audio/22.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(23,'no tears left to cry<br><div class="subtitle">Ariana Grande</div>','img/23.jpg',"If you want it, take it I should have said it before Tried to hide it, fake it I can't pretend anymore I only want to die alive Never by the hands of a broken heart I don't wanna hear you lie tonight Now that I've become who I really am This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more You were better, deeper I was under your spell Like a deadly fear I am, babe On the highway to hell I only want to die alive Never by the hands of a broken heart I don't wanna hear you lie tonight Now that I've become who I really am This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more Thought of your body I came alive It was lethal It was fatal In my dreams it felt so right But I woke up every time Oh baby This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more",'audio/23.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(24,'Girl like you <br><div class="subtitle">Maroon 5 ft Cardi B</div>','img/24.jpg',"If you want it, take it I should have said it before Tried to hide it, fake it I can't pretend anymore I only want to die alive Never by the hands of a broken heart I don't wanna hear you lie tonight Now that I've become who I really am This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more You were better, deeper I was under your spell Like a deadly fear I am, babe On the highway to hell I only want to die alive Never by the hands of a broken heart I don't wanna hear you lie tonight Now that I've become who I really am This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more Thought of your body I came alive It was lethal It was fatal In my dreams it felt so right But I woke up every time Oh baby This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more",'audio/24.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(25,'Anti hero<br><div class="subtitle">Taylor Swift</div>','img/25.jpg',"If you want it, take it I should have said it before Tried to hide it, fake it I can't pretend anymore I only want to die alive Never by the hands of a broken heart I don't wanna hear you lie tonight Now that I've become who I really am This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more You were better, deeper I was under your spell Like a deadly fear I am, babe On the highway to hell I only want to die alive Never by the hands of a broken heart I don't wanna hear you lie tonight Now that I've become who I really am This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more Thought of your body I came alive It was lethal It was fatal In my dreams it felt so right But I woke up every time Oh baby This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more",'audio/25.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(26,'Unholy <br><div class="subtitle">Sam Smith, Kim Petras</div>','img/26.jpg',"If you want it, take it I should have said it before Tried to hide it, fake it I can't pretend anymore I only want to die alive Never by the hands of a broken heart I don't wanna hear you lie tonight Now that I've become who I really am This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more You were better, deeper I was under your spell Like a deadly fear I am, babe On the highway to hell I only want to die alive Never by the hands of a broken heart I don't wanna hear you lie tonight Now that I've become who I really am This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more Thought of your body I came alive It was lethal It was fatal In my dreams it felt so right But I woke up every time Oh baby This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more This is the part when I say I don't want ya I'm stronger than I've been before This is the part when I break free 'Cause I can't resist it no more",'audio/26.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(27,'Break free<br><div class="subtitle">Ariana Grande</div>','img/27.jpg',"Heaven sent you to me I'm just hopin' I don't repeat history Boy, I'm tryna meet your mama on a Sunday Then make a lotta love on a Monday (ah-ah) Never need no (no), no one else, babe 'Cause I'll be Switchin' the positions for you Cookin' in the kitchen, and I'm in the bedroom I'm in the Olympics, way I'm jumpin' through hoops Know my love infinite, nothin' I wouldn't do That I won't do, switchin' for y- Perfect, perfect You're too good to be true (you're too good to be true) But I get tired of runnin' Fuck it, now I'm runnin' with you (wit' you) Said, boy, I'm tryna meet your mama on a Sunday Then make a lotta love on a Monday (ah-ah) Never need no (no), no one else, babе 'Cause I'll be Switchin' the positions for you (for you, ah) Cookin' in thе kitchen, and I'm in the bedroom I'm in the Olympics, way I'm jumpin' through hoops Know my love infinite, nothin' I wouldn't do That I won't do, switchin' for you Cookin' in the kitchen, and I'm in the bedroom (bedroom) I'm in the Olympics, way I'm jumpin' through hoops Know my love infinite, nothin' I wouldn't do That I won't do, switchin' for you This some shit that I usually don't do (yeah) But for you, I kinda, kinda want to 'Cause you're down for me, and I'm down too (and I'm down too) Yeah, I'm down too, switching the positions for you This some shit that I (yeah) usually don't do (don't do) But for you, I kinda, kinda want to 'Cause you're down for me, and I'm down too Switchin' the positions for you Cookin' in the kitchen, and I'm in the bedroom I'm in the Olympics, way I'm jumpin' through hoops (to you, to you) Know my love infinite, nothin' I wouldn't do (do) That I won't do, switchin' for you Cookin' in the kitchen and I'm in the bedroom I'm in the Olympics, way I'm jumpin' through hoops Know my love infinite, nothin' I wouldn't do That I won't do, switchin' for you Yeah Ah, yeah Ah (ah), yeah",'audio/27.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(28,'Positions<br><div class="subtitle">Ariana Grande</div>','img/28.jpg',"Alright Ooh, yeah I'll admit, I was wrong, what else can I say, girl? Can't you blame my head and not my heart? I was drunk, I was gone, that don't make it right, but I promise there were no feelings involved, mmh She said, 'Boy, tell me honestly Was it real or just for show?', yeah She said, 'Save your apologies Baby, I just gotta know' How long has this been goin' on? You been creepin' 'round on me While you're callin' me baby How long has this been goin' on? You've been actin' so shady (shady) I've been feelin' it lately, baby Ooo-oh (yeah) Ooo-oh (encore) Oooh-ooh-oh I'll admit (I'll admit), it's my fault (my fault), but you gotta believe me When I say it only happened once, mmh I try (I try), and I try (I try), but you'll never see that You're the only I wanna love, oh, yeah She said 'Boy, tell me honestly' (honestly) Was it real or just for show?, yeah (real or just for show?) She said, Save your apologies (apologies, yeah) Baby, I just gotta know How long has this been goin' on? You been creepin' 'round on me (on me) While you're callin' me baby (baby) How long has this been goin' on? You've been actin' so shady (shady) I've been feelin' it lately (lately), baby Ooo-oh (yeah) Ooo-oh (encore) Oooh-ooh-oh How long has it been goin' on, baby? Ooo-oh (yeah) Ooo-oh, you gotta go tell me now Oooh-ooh-oh She said, Boy, tell me honestly Was it real or just for show?, yeah She said, Save your apologies Baby, I just gotta know How long has this been goin' on? (on, on) You been creepin' 'round on me (on me) While you're callin' me  (baby) How long has this been goin' on? You've been actin' so shady (shady) I've been feelin' it lately (lately), baby How long has this been goin' on? (ooh-ooh, yeah) You've been creepin' 'round on me How long has it been goin' on, baby? Oh (ooo-oh) How long has this been goin' on? (You gotta go tell me now) You've been actin' so shady (shady) I've been feelin' it lately, baby",'audio/28.mp3','2019-02-12 06:22:25');

INSERT INTO songs value(29,'How long<br><div class="subtitle">Charlie Puth</div>','img/29.jpg',"Alright Ooh, yeah I'll admit, I was wrong, what else can I say, girl? Can't you blame my head and not my heart? I was drunk, I was gone, that don't make it right, but I promise there were no feelings involved, mmh She said, 'Boy, tell me honestly Was it real or just for show?', yeah She said, 'Save your apologies Baby, I just gotta know' How long has this been goin' on? You been creepin' 'round on me While you're callin' me baby How long has this been goin' on? You've been actin' so shady (shady) I've been feelin' it lately, baby Ooo-oh (yeah) Ooo-oh (encore) Oooh-ooh-oh I'll admit (I'll admit), it's my fault (my fault), but you gotta believe me When I say it only happened once, mmh I try (I try), and I try (I try), but you'll never see that You're the only I wanna love, oh, yeah She said 'Boy, tell me honestly' (honestly) Was it real or just for show?, yeah (real or just for show?) She said, Save your apologies (apologies, yeah) Baby, I just gotta know How long has this been goin' on? You been creepin' 'round on me (on me) While you're callin' me baby (baby) How long has this been goin' on? You've been actin' so shady (shady) I've been feelin' it lately (lately), baby Ooo-oh (yeah) Ooo-oh (encore) Oooh-ooh-oh How long has it been goin' on, baby? Ooo-oh (yeah) Ooo-oh, you gotta go tell me now Oooh-ooh-oh She said, Boy, tell me honestly Was it real or just for show?, yeah She said, Save your apologies Baby, I just gotta know How long has this been goin' on? (on, on) You been creepin' 'round on me (on me) While you're callin' me  (baby) How long has this been goin' on? You've been actin' so shady (shady) I've been feelin' it lately (lately), baby How long has this been goin' on? (ooh-ooh, yeah) You've been creepin' 'round on me How long has it been goin' on, baby? Oh (ooo-oh) How long has this been goin' on? (You gotta go tell me now) You've been actin' so shady (shady) I've been feelin' it lately, baby",'audio/29.mp3','2019-02-12 06:22:25');


INSERT INTO songs value(30,'Boy Friend<br><div class="subtitle">Justin Bieber</div>','img/30.jpg',"Heaven sent you to me I'm just hopin' I don't repeat history Boy, I'm tryna meet your mama on a Sunday Then make a lotta love on a Monday (ah-ah) Never need no (no), no one else, babe 'Cause I'll be Switchin' the positions for you Cookin' in the kitchen, and I'm in the bedroom I'm in the Olympics, way I'm jumpin' through hoops Know my love infinite, nothin' I wouldn't do That I won't do, switchin' for y- Perfect, perfect You're too good to be true (you're too good to be true) But I get tired of runnin' Fuck it, now I'm runnin' with you (wit' you) Said, boy, I'm tryna meet your mama on a Sunday Then make a lotta love on a Monday (ah-ah) Never need no (no), no one else, babе 'Cause I'll be Switchin' the positions for you (for you, ah) Cookin' in thе kitchen, and I'm in the bedroom I'm in the Olympics, way I'm jumpin' through hoops Know my love infinite, nothin' I wouldn't do That I won't do, switchin' for you Cookin' in the kitchen, and I'm in the bedroom (bedroom) I'm in the Olympics, way I'm jumpin' through hoops Know my love infinite, nothin' I wouldn't do That I won't do, switchin' for you This some shit that I usually don't do (yeah) But for you, I kinda, kinda want to 'Cause you're down for me, and I'm down too (and I'm down too) Yeah, I'm down too, switching the positions for you This some shit that I (yeah) usually don't do (don't do) But for you, I kinda, kinda want to 'Cause you're down for me, and I'm down too Switchin' the positions for you Cookin' in the kitchen, and I'm in the bedroom I'm in the Olympics, way I'm jumpin' through hoops (to you, to you) Know my love infinite, nothin' I wouldn't do (do) That I won't do, switchin' for you Cookin' in the kitchen and I'm in the bedroom I'm in the Olympics, way I'm jumpin' through hoops Know my love infinite, nothin' I wouldn't do That I won't do, switchin' for you Yeah Ah, yeah Ah (ah), yeah",'audio/30.mp3','2019-02-12 06:22:25');

insert into category value(1,'Nhạc POP','Thể loại nhạc sôi động cuốn hút');
insert into category value(2,'Nhạc RAP','Thể loại nhạc đọc lời');
insert into category value(3,'Nhạc anh','Thể loại nhạc nước ngoài đa dạng');


insert into `comments` value(1,1,1,"Bài này hay quá xá","2019-02-12 13:22:43");
insert into `comments` value(2,1,1,"Bài này hay quá xá 2","2019-02-12 13:22:43");
insert into `comments` value(3,1,1,"Bài này hay quá xá 3","2019-02-12 13:22:43");
